//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/amin/Documents/Fapla/fapla-antlr/Fapla.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFaplaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class FaplaBaseListener : IFaplaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.startState"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStartState([NotNull] FaplaParser.StartStateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.startState"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStartState([NotNull] FaplaParser.StartStateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.moduleDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleDeclaration([NotNull] FaplaParser.ModuleDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.moduleDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleDeclaration([NotNull] FaplaParser.ModuleDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.mainModuleDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainModuleDeclaration([NotNull] FaplaParser.MainModuleDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.mainModuleDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainModuleDeclaration([NotNull] FaplaParser.MainModuleDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.moduleInput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleInput([NotNull] FaplaParser.ModuleInputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.moduleInput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleInput([NotNull] FaplaParser.ModuleInputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.moduleOutput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleOutput([NotNull] FaplaParser.ModuleOutputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.moduleOutput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleOutput([NotNull] FaplaParser.ModuleOutputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] FaplaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] FaplaParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] FaplaParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] FaplaParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] FaplaParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] FaplaParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] FaplaParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] FaplaParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] FaplaParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] FaplaParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.varDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclaration([NotNull] FaplaParser.VarDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.varDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclaration([NotNull] FaplaParser.VarDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] FaplaParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] FaplaParser.AssignmentContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
