//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/amin/Documents/Fapla/fapla-antlr/Fapla.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FaplaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface IFaplaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.startState"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartState([NotNull] FaplaParser.StartStateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.startState"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartState([NotNull] FaplaParser.StartStateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.moduleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleDeclaration([NotNull] FaplaParser.ModuleDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.moduleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleDeclaration([NotNull] FaplaParser.ModuleDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.mainModuleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainModuleDeclaration([NotNull] FaplaParser.MainModuleDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.mainModuleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainModuleDeclaration([NotNull] FaplaParser.MainModuleDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.moduleInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleInput([NotNull] FaplaParser.ModuleInputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.moduleInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleInput([NotNull] FaplaParser.ModuleInputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.moduleOutput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleOutput([NotNull] FaplaParser.ModuleOutputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.moduleOutput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleOutput([NotNull] FaplaParser.ModuleOutputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] FaplaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] FaplaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] FaplaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] FaplaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] FaplaParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] FaplaParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] FaplaParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] FaplaParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] FaplaParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] FaplaParser.PrimitiveTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclaration([NotNull] FaplaParser.VarDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclaration([NotNull] FaplaParser.VarDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FaplaParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] FaplaParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FaplaParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] FaplaParser.AssignmentContext context);
}
